# Generated by Django 5.0.7 on 2024-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
