# Generated by Django 5.0.7 on 2024-08-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_pacientes_id_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='otro_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
